---
version: "3"
services:
  simpleservice:
    image: "simpleservice"
    build: "./SimpleService"
  activemq:
    image: "activemq"
    build: "./activemq"
    ports:
    - "61616:61616"
  accountdb:
    image: "accountdb"
    build: "./AccountDB"
  couchbase:
    image: "couchbase"
    build: "./couchbase"
    ports:
    - "8091-8094:8091-8094"
    - "11210:11210"
  testclient:
    image: "testclient"
    build: "./TestClient"
  accountservice:
    image: "accountservice"
    build: "./AccountService"
  gatewayservice:
    image: "gatewayservice"
    build: "./GatewayService"
