---
version: "3"
services:
  activemq:
    image: "activemq"
    build: "activemq"
    networks:
    - "mn_bridge_network"
    ports:
    - "61616:61616"
  playerservice:
    image: "playerservice"
    build: "PlayerService"
    networks:
    - "mn_bridge_network"
networks:
  mn_bridge_network:
    external:
      name: "mn_bridge_network"
