version: "2.1"
services:


# Avatar Service Definition

  avatar-service:
    build: ./AvatarService
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    links:
      - activemq
      - avatar-db
    command: "/wait-for-it.sh activemq:61616 -- /wait-for-it.sh account-db:5432 -- java -cp ./target/classes:./target/lib/* ServiceImpl"

  avatar-db:
    build: ./AvatarDB

# Account Service Definition

  account-service:
    build: ./AccountService
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    links:
      - activemq
      - account-db
    command: "/wait-for-it.sh activemq:61616 -- /wait-for-it.sh account-db:5432 -- java -cp ./target/classes:./target/lib/* ServiceImpl"

  account-db:
    build: ./AccountDB

# Message Broker
   
  activemq:
    image: "webcenter/activemq:latest"
    ports:
      - 61111:61616