---
version: "3"
services:
  roundservice:
    image: "roundservice"
    build: "./RoundService"
  voteservice:
    image: "voteservice"
    build: "./VoteService"
  playerservice:
    image: "playerservice"
    build: "./PlayerService"
  accountservice:
    image: "accountservice"
    build: "./AccountService"
  gatewayservice:
    image: "gatewayservice"
    build: "./GatewayService"
