---
version: "3"
services:
  activemq:
    image: "activemq"
    build: "activemq"
    networks:
    - "bridge"
    ports:
    - "61616:61616"
  playerservice:
    image: "playerservice"
    build: "PlayerService"
    networks:
    - "bridge"
networks:
  bridge:
    external:
      name: "bridge"
